# agent/llm/client.py

"""
Oracle LLM Client - A high-level interface for multi-provider support.

This module provides the LLMClient class which decouples the core logic
from specific provider implementations via the ProviderFactory.
"""

from typing import List, Dict
from agent.llm.factory import ProviderFactory

class LLMClient:
    """
    Central LLM abstraction for Oracle.

    Acts as a managed wrapper around the factory-selected provider,
    ensuring a consistent interface for the rest of the application.
    """

    def __init__(self):
        """
        Initializes the client by obtaining the default provider from the factory.
        """
        # The factory handles selection and provider-specific validation (like API keys)
        self.provider = ProviderFactory.get_provider()

    def generate(self, messages: List[Dict[str, str]]) -> str:
        """
        Delegates generation to the factory-selected provider.

        Args:
            messages: A list of message dictionaries (role/content) representing the conversation.

        Returns:
            str: The text content generated by the LLM.
        """
        return self.provider.generate(messages)
