/**
 * FixtureSet -> a literal-only vitest fixture module (#765). The emitted text
 * holds no PRNG, clock or generator call: every value was decided at emit
 * time, so the file is byte-identical for a given (schema, seed) and a reader
 * sees exactly what the test runs against.
 */
import type { FixtureSet } from './generate.js';
import type { ShapeNode } from './shape.js';

const IDENT = /^[A-Za-z_$][\w$]*$/;
const pad = (depth: number) => '  '.repeat(depth);
const renderKey = (k: string) => (IDENT.test(k) ? k : JSON.stringify(k));

export function fixtureNames(name: string): { pascal: string; camel: string } {
  const pascal = name
    .split(/[^A-Za-z0-9]+/)
    .filter((w) => w.length > 0)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join('');
  return { pascal, camel: pascal.charAt(0).toLowerCase() + pascal.slice(1) };
}

type Renderer = (node: never, depth: number) => string;
const TYPE_RENDERERS: Record<ShapeNode['kind'], Renderer> = {
  string: (n: Extract<ShapeNode, { kind: 'string' }>) =>
    n.enum ? n.enum.map((v) => quote(v)).join(' | ') : 'string',
  number: () => 'number',
  boolean: () => 'boolean',
  date: () => 'string',
  array: (n: Extract<ShapeNode, { kind: 'array' }>, depth: number) =>
    `Array<${renderType(n.item, depth)}>`,
  object: renderObjectType,
  union: (n: Extract<ShapeNode, { kind: 'union' }>, depth: number) =>
    n.members.map((m) => renderType(m, depth)).join(' | '),
  unresolved: () => 'unknown',
};

function renderType(node: ShapeNode, depth: number): string {
  return (TYPE_RENDERERS[node.kind] as (n: ShapeNode, d: number) => string)(
    node,
    depth,
  );
}

function renderObjectType(
  n: Extract<ShapeNode, { kind: 'object' }>,
  depth: number,
): string {
  const entries = Object.entries(n.fields);
  if (entries.length === 0) return '{}';
  // Nested unresolved fields are omitted from the default and cannot be
  // guarded through `overrides`, so they are typed optional.
  const lines = entries.map(([k, f]) => {
    const optional = f.optional || (depth > 0 && f.node.kind === 'unresolved');
    return `${pad(depth + 1)}${renderKey(k)}${optional ? '?' : ''}: ${renderType(f.node, depth + 1)};`;
  });
  return `{\n${lines.join('\n')}\n${pad(depth)}}`;
}

/** Single-quoted TS string literal. */
function quote(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function renderLiteral(value: unknown, depth: number): string {
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map(
      (v) => `${pad(depth + 1)}${renderLiteral(v, depth + 1)},`,
    );
    return `[\n${items.join('\n')}\n${pad(depth)}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    const lines = entries.map(
      ([k, v]) =>
        `${pad(depth + 1)}${renderKey(k)}: ${renderLiteral(v, depth + 1)},`,
    );
    return `{\n${lines.join('\n')}\n${pad(depth)}}`;
  }
  return value === undefined ? 'undefined' : JSON.stringify(value);
}

function renderHeader(set: FixtureSet, source: string): string {
  const unresolved = set.unresolved.map((u) => `\n// - ${u.path}: ${u.reason}`);
  return [
    `// Generated by canary gen-data (seed ${set.seed}) from ${source}. Regenerate; do not edit.`,
    `// Fields resolved: ${set.fieldsResolved}/${set.fieldsTotal}.${unresolved.join('')}`,
  ].join('\n');
}

function unresolvedTopKeys(shape: ShapeNode): string[] {
  if (shape.kind !== 'object') return [];
  return Object.entries(shape.fields)
    .filter(([, f]) => f.node.kind === 'unresolved')
    .map(([k]) => k);
}

function renderGuard(shape: ShapeNode, set: FixtureSet, key: string): string {
  const node = shape.kind === 'object' ? shape.fields[key]?.node : undefined;
  const reason = node?.kind === 'unresolved' ? node.reason : 'unresolved';
  const message = `gen-data: ${set.name}.${key} is unresolved (${reason}); pass it via overrides`;
  return [
    `  if (overrides${IDENT.test(key) ? `.${key}` : `[${JSON.stringify(key)}]`} === undefined) {`,
    `    throw new Error(${quote(message)});`,
    '  }',
  ].join('\n');
}

function renderBuilder(
  shape: ShapeNode,
  set: FixtureSet,
  pascal: string,
): string {
  const keys = unresolvedTopKeys(shape);
  const omitted = keys.length ? keys.map(quote).join(' | ') : 'never';
  const guards = keys.map((k) => `${renderGuard(shape, set, k)}\n`).join('');
  return [
    `export function build${pascal}(`,
    `  overrides: Partial<${pascal}Fixture> = {},`,
    `): ${pascal}Fixture {`,
    `${guards}  const base: Omit<${pascal}Fixture, ${omitted}> = ${renderLiteral(set.defaultValue, 1)};`,
    `  return { ...base, ...overrides } as ${pascal}Fixture;`,
    '}',
  ].join('\n');
}

function renderCases(set: FixtureSet, camel: string): string {
  const rows = set.cases.map((c) =>
    [
      '  {',
      `    name: ${JSON.stringify(c.name)},`,
      `    category: ${JSON.stringify(c.category)},`,
      `    value: ${renderLiteral(c.value, 2)},`,
      '  },',
    ].join('\n'),
  );
  return [
    `export const ${camel}Cases: ReadonlyArray<{`,
    '  name: string;',
    '  category: string;',
    '  value: unknown;',
    rows.length ? `}> = [\n${rows.join('\n')}\n];` : '}> = [];',
  ].join('\n');
}

export function emitVitest(
  shape: ShapeNode,
  set: FixtureSet,
  source: string,
): string {
  const { pascal, camel } = fixtureNames(set.name);
  return (
    [
      renderHeader(set, source),
      `export interface ${pascal}Fixture ${renderType(shape, 0)}`,
      renderBuilder(shape, set, pascal),
      renderCases(set, camel),
    ].join('\n\n') + '\n'
  );
}
