/**
 * Permission matrix (#857): a human-declared allow/deny grid, expanded across
 * every acting tenant x target tenant, rendered as server-direct API tests.
 *
 * The grid is declared, never inferred. Inferring expectations from current
 * behaviour would encode today's authz bugs as "expected". So a cell with no
 * declaration is `undeclared` -- counted and named, never allowed or denied by
 * default -- because a default is exactly where the cells nobody thought about
 * would hide.
 */

import { load } from 'js-yaml';

export type CellValue = 'allow' | 'deny' | 'own-tenant';
const VALUES: readonly string[] = ['allow', 'deny', 'own-tenant'];

export interface MatrixModel {
  roles: string[];
  tenants: string[];
  endpoints: Record<string, Record<string, unknown>>;
}

export interface Cell {
  endpoint: string;
  method: string;
  path: string;
  role: string;
  actingTenant: string;
  targetTenant: string;
  expect: 'allow' | 'deny' | 'undeclared';
}

// Backtick, `$` and backslash are excluded from paths because the path is
// spliced into a generated template literal.
const ENDPOINT = /^([A-Z]+)\s+(\/[^\s`$\\]*)$/;

function stringList(v: unknown, key: string): string[] {
  if (
    !Array.isArray(v) ||
    v.length === 0 ||
    !v.every((x) => typeof x === 'string')
  ) {
    throw new Error(`model needs a non-empty "${key}" list of names`);
  }
  return v as string[];
}

export function parseMatrix(text: string): MatrixModel {
  const raw = (load(text) ?? {}) as Record<string, unknown>;
  const roles = stringList(raw['roles'], 'roles');
  const tenants = stringList(raw['tenants'], 'tenants');
  const endpoints = raw['endpoints'];
  if (
    endpoints === null ||
    typeof endpoints !== 'object' ||
    Array.isArray(endpoints)
  ) {
    throw new Error(
      'model needs an "endpoints" map of "METHOD /path" -> cells',
    );
  }
  for (const key of Object.keys(endpoints)) {
    if (!ENDPOINT.test(key)) {
      throw new Error(`endpoint "${key}" must be written as "METHOD /path"`);
    }
  }
  return {
    roles,
    tenants,
    endpoints: endpoints as Record<string, Record<string, unknown>>,
  };
}

export function expandMatrix(model: MatrixModel): {
  cells: Cell[];
  undeclared: string[];
} {
  const cells: Cell[] = [];
  const undeclared: string[] = [];
  for (const [endpoint, row] of Object.entries(model.endpoints)) {
    const [, method, path] = ENDPOINT.exec(endpoint)!;
    for (const role of model.roles) {
      const declared = (row ?? {})[role];
      let value: CellValue | null = null;
      if (declared === undefined) {
        undeclared.push(`${endpoint} × ${role}`);
      } else if (typeof declared !== 'string' || !VALUES.includes(declared)) {
        undeclared.push(
          `${endpoint} × ${role} (unknown value "${String(declared)}")`,
        );
      } else {
        value = declared as CellValue;
      }
      for (const actingTenant of model.tenants) {
        for (const targetTenant of model.tenants) {
          cells.push({
            endpoint,
            method: method!,
            path: path!,
            role,
            actingTenant,
            targetTenant,
            expect:
              value === null
                ? 'undeclared'
                : value === 'own-tenant'
                  ? actingTenant === targetTenant
                    ? 'allow'
                    : 'deny'
                  : value,
          });
        }
      }
    }
  }
  return { cells, undeclared };
}

/** Env-var-safe form of a role or tenant name. */
export function envName(s: string): string {
  return s.toUpperCase().replace(/[^A-Z0-9]/g, '_');
}

export function renderPlaywright(cells: Cell[]): string {
  const lines = [
    '// Generated by `canary permission-matrix` (#857). Do not edit by hand:',
    '// change the declared model and regenerate.',
    '//',
    '// Credentials and fixtures come from the environment, never this file:',
    '//   CANARY_TOKEN_<ROLE>_<TENANT>  bearer token for that role in that tenant',
    '//   CANARY_ID_<TENANT>            a synthetic record owned by that tenant',
    "import { test, expect } from '@playwright/test';",
    '',
    'function env(name: string): string {',
    '  const v = process.env[name];',
    '  // A missing credential must fail, not skip: a skipped deny cell reads as',
    '  // "no leak" in the report.',
    '  if (!v) throw new Error(`${name} is not set`);',
    '  return v;',
    '}',
    '',
    'const DENIED = [401, 403, 404];',
    '',
  ];
  for (const c of cells) {
    const verb =
      c.expect === 'allow'
        ? 'allowed'
        : c.expect === 'deny'
          ? 'denied'
          : 'UNDECLARED';
    const title = JSON.stringify(
      `${c.role}@${c.actingTenant} -> ${c.targetTenant}: ${c.endpoint} is ${verb}`,
    );
    if (c.expect === 'undeclared') {
      lines.push(
        `test.fixme(${title}, () => {`,
        '  // UNDECLARED: the model has no expectation for this cell. Declare it.',
        '});',
        '',
      );
      continue;
    }
    const url = c.path.replace(
      /\{[^}]+\}/g,
      `\${env('CANARY_ID_${envName(c.targetTenant)}')}`,
    );
    lines.push(
      `test(${title}, async ({ request }) => {`,
      `  const res = await request.fetch(\`${url}\`, {`,
      `    method: '${c.method}',`,
      `    headers: { Authorization: \`Bearer \${env('CANARY_TOKEN_${envName(c.role)}_${envName(c.actingTenant)}')}\` },`,
      '  });',
      c.expect === 'allow'
        ? '  expect(res.status()).toBeLessThan(400);'
        : '  expect(DENIED).toContain(res.status());',
      '});',
      '',
    );
  }
  return lines.join('\n');
}
