/**
 * Contract tests for `scripts/gemini-commands-drift.mjs` (#1249).
 *
 * `agents/commands/gemini-cli/harness/*.toml` are generated by
 * `harness generate-slash-commands` from each skill's `SKILL.md` and say "Do
 * not edit", but nothing regenerated or checked them: they sat unchanged from
 * 2026-07-19 while their sources moved on, and six skills never got a Gemini
 * command at all. The script regenerates into a temp dir and diffs.
 *
 * Two halves:
 *   - a FAKE generator (a node script handed over through `HARNESS_BIN`) pins
 *     the contract offline: clean, planted drift, a stale extra file, a
 *     missing file, `--write`, and every abstention (no generator, a crashing
 *     generator, zero output, no skills);
 *   - the REAL repo checked with the REAL generator. That case needs the
 *     harness CLI on PATH, which the TS engine CI job does not install, so it
 *     runs locally only. CI enforcement is the gate step in the `validate` job
 *     of `.github/workflows/harness-quality.yml`, which runs the same script
 *     with the pinned `$HARNESS_CLI` and fails (exit 3) when the generator is
 *     absent rather than passing.
 */

import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { runCapture } from './subprocess-testkit.js';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const SCRIPT = join(REPO_ROOT, 'scripts', 'gemini-commands-drift.mjs');
const REGEN = 'node scripts/gemini-commands-drift.mjs --write';
const OUT_DIR = join('agents', 'commands', 'gemini-cli', 'harness');

/**
 * Stands in for `harness generate-slash-commands`: one `<skill>.toml` per
 * skill directory, holding that skill's SKILL.md, written where the real
 * generator writes (cwd-relative). `FAKE_GEN` picks a failure mode.
 */
const FAKE_GENERATOR = `#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
if (process.argv.includes('--version')) { console.log('12.0.0-fake'); process.exit(0); }
const mode = process.env.FAKE_GEN || 'ok';
if (mode === 'crash') { console.error('generator exploded'); process.exit(1); }
const out = path.join('agents', 'commands', 'gemini-cli', 'harness');
fs.mkdirSync(out, { recursive: true });
if (mode === 'empty') process.exit(0);
const skills = path.join('agents', 'skills', 'claude-code');
for (const name of fs.readdirSync(skills)) {
  const body = fs.readFileSync(path.join(skills, name, 'SKILL.md'), 'utf-8');
  fs.writeFileSync(path.join(out, name + '.toml'), '# generated\\n' + body);
}
`;

let root: string;
let generator: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'gemini-drift-'));
  generator = join(root, 'fake-harness.cjs');
  writeFileSync(generator, FAKE_GENERATOR, 'utf-8');
  chmodSync(generator, 0o755);
});
afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

function writeAt(rel: string, body: string): void {
  const full = join(root, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, body, 'utf-8');
}

/** A repo whose committed commands match what the fake generator emits. */
function inSyncRepo(): void {
  for (const name of ['canary-alpha', 'canary-beta']) {
    const body = `# ${name}\n`;
    writeAt(join('agents', 'skills', 'claude-code', name, 'SKILL.md'), body);
    writeAt(join(OUT_DIR, `${name}.toml`), `# generated\n${body}`);
  }
}

function check(args: string[] = [], env: NodeJS.ProcessEnv = {}) {
  return runCapture('node', [SCRIPT, '--root', root, ...args], {
    env: { ...process.env, HARNESS_BIN: generator, ...env },
  });
}

describe('gemini-commands-drift — in sync', () => {
  it('exits 0 and states the denominator', () => {
    inSyncRepo();
    const r = check();
    expect(r.status, r.output).toBe(0);
    expect(r.output).toMatch(/2 of 2 gemini-cli commands match/);
  });
});

describe('gemini-commands-drift — drift is a failure', () => {
  it('a SKILL.md edited after generation (the #1249 shape) exits 1', () => {
    inSyncRepo();
    writeAt(
      join('agents', 'skills', 'claude-code', 'canary-alpha', 'SKILL.md'),
      '# canary-alpha\n\nNew guidance the committed copy never got.\n',
    );
    const r = check();
    expect(r.status, r.output).toBe(1);
    expect(r.output).toMatch(/changed: canary-alpha\.toml/);
    expect(r.output).toContain(REGEN);
  });

  it('a skill with no committed command exits 1', () => {
    inSyncRepo();
    writeAt(
      join('agents', 'skills', 'claude-code', 'canary-gamma', 'SKILL.md'),
      '# canary-gamma\n',
    );
    const r = check();
    expect(r.status, r.output).toBe(1);
    expect(r.output).toMatch(/missing: canary-gamma\.toml/);
    expect(r.output).toContain(REGEN);
  });

  it('a committed command the generator no longer emits exits 1', () => {
    inSyncRepo();
    writeAt(join(OUT_DIR, 'canary-retired.toml'), '# generated\nold\n');
    const r = check();
    expect(r.status, r.output).toBe(1);
    expect(r.output).toMatch(/stale: canary-retired\.toml/);
  });

  it('--write regenerates the set, after which the check passes', () => {
    inSyncRepo();
    writeAt(join(OUT_DIR, 'canary-retired.toml'), 'old\n');
    writeAt(join(OUT_DIR, 'canary-beta.toml'), 'hand edited\n');
    expect(check(['--write']).status).toBe(0);
    expect(readdirSync(join(root, OUT_DIR)).sort()).toEqual([
      'canary-alpha.toml',
      'canary-beta.toml',
    ]);
    expect(readFileSync(join(root, OUT_DIR, 'canary-beta.toml'), 'utf-8')).toBe(
      '# generated\n# canary-beta\n',
    );
    expect(check().status).toBe(0);
  });
});

describe('gemini-commands-drift — abstains (exit 3), never passes', () => {
  it('when the generator is not installed', () => {
    inSyncRepo();
    const r = check([], { HARNESS_BIN: join(root, 'no-such-harness') });
    expect(r.status, r.output).toBe(3);
    expect(r.output).toMatch(/ABSTAINED/);
    expect(r.output).not.toMatch(/match a fresh generation/);
  });

  it('when the generator exits non-zero', () => {
    inSyncRepo();
    const r = check([], { FAKE_GEN: 'crash' });
    expect(r.status, r.output).toBe(3);
    expect(r.output).toMatch(/generator exploded/);
  });

  it('when the generator emits zero commands', () => {
    inSyncRepo();
    const r = check([], { FAKE_GEN: 'empty' });
    expect(r.status, r.output).toBe(3);
    expect(r.output).toMatch(/0 commands/);
  });

  it('when there is no skills tree to generate from', () => {
    const r = check();
    expect(r.status, r.output).toBe(3);
  });

  it('--write never writes from an abstained generation', () => {
    inSyncRepo();
    const r = check(['--write'], { FAKE_GEN: 'empty' });
    expect(r.status).toBe(3);
    expect(readdirSync(join(root, OUT_DIR))).toHaveLength(2);
  });
});

const hasHarness = !spawnSync('harness', ['--version']).error;

/**
 * The reproducing case for #1249: the committed set against a fresh
 * generation by the real CLI. Red on main before the regeneration (6 changed,
 * 6 missing), green after. Local-only: see the file header for where CI
 * enforces it.
 */
describe.runIf(hasHarness)('gemini-commands-drift — this repository', () => {
  it('the committed gemini-cli commands match a fresh generation', () => {
    const r = runCapture('node', [SCRIPT], {
      env: { ...process.env, HARNESS_BIN: 'harness' },
    });
    expect(r.status, r.output).toBe(0);
  }, 60_000);
});
