import { describe, expect, it } from 'vitest';
import { emitVitest } from '../src/core/gen-data/emit-vitest.js';
import { generateFixtureSet } from '../src/core/gen-data/generate.js';
import { extractJsonSchema } from '../src/core/gen-data/json-schema.js';

const shape = extractJsonSchema({
  type: 'object',
  required: ['id', 'meta'],
  properties: {
    id: { type: 'string' },
    total: { type: 'number' },
    meta: {},
  },
});
const text = () =>
  emitVitest(
    shape,
    generateFixtureSet(shape, 'order', 765),
    'fixtures/order.schema.json',
  );

describe('emitVitest', () => {
  it('exports buildOrder, OrderFixture and orderCases', () => {
    expect(text()).toMatch(/export interface OrderFixture \{/);
    expect(text()).toMatch(
      /export function buildOrder\(\s*overrides: Partial<OrderFixture> = \{\},?\s*\): OrderFixture/,
    );
    expect(text()).toMatch(/export const orderCases: ReadonlyArray<\{/);
  });
  it('holds literals only: no PRNG, clock, or runtime generator call', () => {
    expect(text()).not.toMatch(
      /Math\.random|Date\.now|new Date\(|mulberry32|faker/,
    );
  });
  it('builds a fresh object per call (no shared module-level default)', () => {
    expect(text()).toMatch(
      /export function buildOrder[\s\S]*const base[^=]*= \{/,
    );
  });
  it('an unresolved field becomes a throwing overrides-required placeholder', () => {
    expect(text()).toContain('  meta: unknown;');
    expect(text()).toContain(
      "throw new Error('gen-data: order.meta is unresolved (no type declared); pass it via overrides');",
    );
  });
  it('header names seed and source, with no timestamp', () => {
    expect(text().split('\n')[0]).toBe(
      '// Generated by canary gen-data (seed 765) from fixtures/order.schema.json. Regenerate; do not edit.',
    );
  });
  it('is byte-identical across runs', () => {
    expect(text()).toBe(text());
  });
});
