#!/usr/bin/env node
// Fail if a harness-generated hook lost a canary-local customization (#318 C).
//
// Several hooks under `.harness/hooks/` are generated by harness but carry
// hand-applied canary edits (commit 6be522e): the quality gate was made to
// actually block on real violations, the formatter was fixed to target the
// edited file (without which the block is a silent no-op), and the telemetry
// hook was deliberately kept non-blocking. Re-running the harness generator
// would clobber those edits and silently revert the hooks to their weaker
// generated form.
//
// The proper fix lives upstream (generator-side preservation, filed there).
// Until it lands, this guard turns a silent clobber into a loud CI failure: it
// asserts each customization's signature is still present. If one is missing, a
// regeneration almost certainly dropped it — re-apply from git history
// (`git show 6be522e`) and re-run this check.
//
// Exit 0 when every customization is present; exit 1 (listing what's missing)
// otherwise. Run in CI and locally after any `harness init`/regeneration.
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');

// hook path (repo-relative) -> list of [signature, why-it-matters]
const CUSTOMIZATIONS = {
  '.harness/hooks/quality-warner.js': [
    [
      'process.exit(2)',
      'blocks on real formatter/linter violations (STRENGTH-001; the ' +
        "generated hook was an unconditional exit-0 'theatre gate')",
    ],
  ],
  '.harness/hooks/format-check.js': [
    [
      "'--', filePath",
      "appends the edited file's path to the formatter args, with a `--` " +
        'option-injection guard (#317 / 6be522e) — without it the blocking ' +
        'gate above runs with no target and is a silent no-op',
    ],
  ],
  '.harness/hooks/telemetry-reporter.js': [
    [
      'actively harmful',
      'the rationale comment for keeping the telemetry Stop-hook ' +
        'non-blocking (a flaky third-party POST must not fail session ' +
        'teardown) — a canary-local decision the generator does not encode',
    ],
  ],
};

/** Return a list of human-readable problems; empty when every hook is intact. */
function check(root = REPO) {
  const problems = [];
  for (const [rel, signatures] of Object.entries(CUSTOMIZATIONS)) {
    let text;
    try {
      text = readFileSync(resolve(root, rel), 'utf-8');
    } catch {
      problems.push(`${rel}: MISSING FILE (expected a customized hook here)`);
      continue;
    }
    for (const [signature, why] of signatures) {
      if (!text.includes(signature)) {
        problems.push(
          `${rel}: lost customization — ${why}\n` +
            `    expected to find: '${signature}'`,
        );
      }
    }
  }
  return problems;
}

function main() {
  const problems = check();
  const total = Object.values(CUSTOMIZATIONS).reduce((n, v) => n + v.length, 0);
  if (problems.length === 0) {
    process.stdout.write(
      `check_hook_customizations: clean — all ${total} canary hook ` +
        'customization(s) present.\n',
    );
    return 0;
  }
  process.stderr.write(
    'check_hook_customizations: a harness-generated hook lost a canary-local ' +
      'edit (a regeneration likely clobbered it).\n' +
      'Re-apply from git history (`git show 6be522e`), then re-run this check.\n\n',
  );
  for (const p of problems) process.stderr.write(`  ✗ ${p}\n`);
  return 1;
}

process.exit(main());
