#!/usr/bin/env python3
"""Fail if a harness-generated hook lost a canary-local customization (#318 C).

Several hooks under ``.harness/hooks/`` are **generated by harness** but carry
hand-applied canary edits (commit ``6be522e``): the quality gate was made to
actually block on real violations, the formatter was fixed to target the edited
file (without which the block is a silent no-op), and the telemetry hook was
deliberately kept non-blocking. Re-running the harness generator would clobber
those edits and silently revert the hooks to their weaker generated form.

The proper fix lives upstream (generator-side preservation, filed there). Until
it lands, this guard turns a silent clobber into a **loud CI failure**: it
asserts each customization's signature is still present. If one is missing, a
regeneration almost certainly dropped it — re-apply from git history
(``git show 6be522e``) and re-run this check.

Exit 0 when every customization is present; exit 1 (listing what's missing)
otherwise. Run in CI and locally after any ``harness init``/regeneration.
"""

from __future__ import annotations

import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[1]

# hook path (repo-relative) -> list of (signature, why-it-matters)
CUSTOMIZATIONS: dict[str, list[tuple[str, str]]] = {
    ".harness/hooks/quality-warner.js": [
        (
            "process.exit(2)",
            "blocks on real formatter/linter violations (STRENGTH-001; the "
            "generated hook was an unconditional exit-0 'theatre gate')",
        ),
    ],
    ".harness/hooks/format-check.js": [
        (
            "'--', filePath",
            "appends the edited file's path to the formatter args, with a `--` "
            "option-injection guard (#317 / 6be522e) — without it the blocking "
            "gate above runs with no target and is a silent no-op",
        ),
    ],
    ".harness/hooks/telemetry-reporter.js": [
        (
            "actively harmful",
            "the rationale comment for keeping the telemetry Stop-hook "
            "non-blocking (a flaky third-party POST must not fail session "
            "teardown) — a canary-local decision the generator does not encode",
        ),
    ],
}


def check(root: Path = _REPO) -> list[str]:
    """Return a list of human-readable problems; empty when every hook is intact."""
    problems: list[str] = []
    for rel, signatures in CUSTOMIZATIONS.items():
        path = root / rel
        try:
            text = path.read_text(encoding="utf-8")
        except OSError:
            problems.append(f"{rel}: MISSING FILE (expected a customized hook here)")
            continue
        for signature, why in signatures:
            if signature not in text:
                problems.append(
                    f"{rel}: lost customization — {why}\n"
                    f"    expected to find: {signature!r}"
                )
    return problems


def main() -> int:
    problems = check()
    if not problems:
        print(
            "check_hook_customizations: clean — all "
            f"{sum(len(v) for v in CUSTOMIZATIONS.values())} canary hook "
            "customization(s) present."
        )
        return 0
    print(
        "check_hook_customizations: a harness-generated hook lost a canary-local "
        "edit (a regeneration likely clobbered it).\n"
        "Re-apply from git history (`git show 6be522e`), then re-run this check.\n",
        file=sys.stderr,
    )
    for p in problems:
        print(f"  ✗ {p}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
